---
abstract: 'My Dist::Zilla plugin bundle'
author:
  - 'Matt Finkel <fffinkel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.005, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-FFFINKEL
requires:
  Dist::Zilla: 4.300036
  Dist::Zilla::Plugin::Authority: 0
  Dist::Zilla::Plugin::AutoPrereqs: 0
  Dist::Zilla::Plugin::ChangelogFromGit: 0
  Dist::Zilla::Plugin::Clean: 0
  Dist::Zilla::Plugin::EOLTests: 0
  Dist::Zilla::Plugin::Git::Check: 0
  Dist::Zilla::Plugin::Git::NextVersion: 0
  Dist::Zilla::Plugin::PodCoverageTests: 0
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::Twitter: 0
  Dist::Zilla::PluginBundle::Basic: 0
  Dist::Zilla::PluginBundle::Filter: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  Pod::Coverage::TrustPod: 0
  Pod::Elemental: 0.092970
  Pod::Elemental::Transformer::List: 0
  Pod::Weaver: 3.100310
  Test::Pod: 1.41
  Test::Pod::Coverage: 1.08
  namespace::autoclean: 0
version: 0.007
x_authority: cpan:FFFINKEL
